DATASET_FINE: /home/emaraic/semanticSegmentation/datasets/cityscapes
DATASET_COARSE: /home/emaraic/semanticSegmentation/datasets/CityscapesExtra

USING_COARSE: False
BACKEND_NETWORK: MOBILENET

USING_GPU: TRUE
GPU_ID: 0

PRETRAINED_SHUFFLENET: /content/LiteSeg
PRETRAINED_MOBILENET: /content/LiteSeg
PRETRAINED_DarkNET19: /home/emaraic/semanticSegmentation/Repos/deeplabResnext/models/darknet19_448.weights

