DATASET_FINE: /content/LiteSeg
DATASET_COARSE: /content/LiteSeg

USING_COARSE: False
BACKEND_NETWORK: MOBILENET

USING_GPU: TRUE
GPU_ID: 0

PRETRAINED_SHUFFLENET: /content/LiteSeg
PRETRAINED_MOBILENET: /content/LiteSeg
PRETRAINED_DarkNET19: /content/LiteSeg

